server:
  port: 8000

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8762/eureka

spring:
  config:
    activate:
      on-profile: dev
  application:
    name: wk-gateway
  cloud:
    gateway:
      routes:
        - id: boardHigh
          uri: lb://BOARDHIGH
          predicates:
            - Path=/boardHigh/**

logging:
  level:
    #    org.springframework.cloud.gateway: trace
    reactor.netty: trace

management:
  endpoints:
    web:
      exposure:
        include: "*"